## NumPy

In [1]:
#Kütüphanemizi np ismi ile import ettik
import numpy as np

In [2]:
#PythonListesi
mylist=[20,30,40]

In [3]:
#NumpyArray
np.array(mylist)

array([20, 30, 40])

## arange

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

## ones

In [7]:
np.ones((3))

array([1., 1., 1.])

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## linspace

In [9]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

## eye()

In [10]:
#4x4'lük birim matris
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random

In [11]:
np.random.randn(4)

array([0.43719736, 0.29258017, 1.16409586, 2.38186997])

In [12]:
np.random.randn(3,3)

array([[ 0.16370869, -0.45783613, -0.47598506],
       [-0.26326574,  1.01643494, -0.82772081],
       [-0.19132065,  2.06157804, -0.41277417]])

In [13]:
np.random.randint(1,10)

1

In [14]:
np.random.randint(1,20,7)

array([19,  2, 11, 12, 12, 11,  4])

## numpy dizi methodları

In [15]:
#rastgele bir dizi oluşturalım
mylist=np.random.randint(1,100,10)

In [16]:
mylist.reshape(5,2)

array([[38, 79],
       [51, 74],
       [73, 43],
       [20, 14],
       [ 1, 91]])

In [17]:
mylist.max()

91

In [18]:
mylist.min()

1

In [19]:
#max elemanın indexi
mylist.argmax()

9

In [20]:
#min elemanın indexi
mylist.argmin()

8

In [21]:
#dizinin boyutu
mylist.shape

(10,)